src/Entity/Annonce.php
<?php

namespace App\Entity;

use App\Repository\AnnonceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AnnonceRepository::class)
 */
class Annonce
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $modified_at;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="annonces")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\Column(type="json", nullable=true)
     */
    private $images = [];

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="annonces")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity=Report::class, mappedBy="annonce")
     */
    private $reports;

    public function __construct()
    {
        $this->reports = new ArrayCollection();
        $this->created_at = new \DateTime();
        $this->modified_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getModifiedAt(): ?\DateTimeInterface
    {
        return $this->modified_at;
    }

    public function setModifiedAt(\DateTimeInterface $modified_at): self
    {
        $this->modified_at = $modified_at;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getImages(): ?array
    {
        return $this->images;
    }

    public function setImages(?array $images): self
    {
        $this->images = $images;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Report[]
     */
    public function getReports(): Collection
    {
        return $this->reports;
    }

    public function addReport(Report $report): self
    {
        if (!$this->reports->contains($report)) {
            $this->reports[] = $report;
            $report->setAnnonce($this);
        }

        return $this;
    }

    public function removeReport(Report $report): self
    {
        if ($this->reports->removeElement($report)) {
            // set the owning side to null (unless already changed)
            if ($report->getAnnonce() === $this) {
                $report->setAnnonce(null);
            }
        }

        return $this;
    }
}

src/Form/AnnonceType.php
<?php

namespace App\Form;

use App\Entity\Annonce;
use App\Entity\Category;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AnnonceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title',TextType::class, [
                "attr" => [
                    "class" => "form__input",
                    "placeholder" =>"Title",
                ]
            ])
            ->add('description', TextareaType::class, [
                "attr" => [
                    "class" => "form__textarea",
                    "placeholder" =>"Description ...",
                ]
            ])
            ->add('images', FileType::class, [
                "attr" => [
                    "class" => "form-control",
                    "accept" => "image/*"
                ],
                "label" => "Select images",
                "required" => true,
                "multiple" => true,
            ])
            ->add('price', NumberType::class, [
                "attr" => [
                    "class" => "form__input",
                    "placeholder" =>"Price",
                ]
            ])
            ->add('category', EntityType::class, [
                    "attr" => [
                        "class" => "filter__select"
                    ],
                    "class" => Category::class,
                    "choice_label" => "name",
                    "multiple" => false,
                    "required" => true
                ]
            )
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Annonce::class,
        ]);
    }
}

src/Controller/AnnonceController.php
<?php

namespace App\Controller;

use App\Entity\Annonce;
use App\Entity\Report;
use App\Form\AnnonceType;
use App\Form\ReportType;
use App\Repository\AnnonceRepository;
use App\Repository\CategoryRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AnnonceController extends AbstractController
{
    /**
     * @Route("/annonce", name="annonce")
     */
    public function index(AnnonceRepository $repository): Response
    {

        $annonces = $repository->findAll();

        return $this->render('annonce/index.html.twig', [
            'annonces' => $annonces
        ]);
    }

    /**
     * @Route("/annonce/add", name="add_annonce")
     * @param Request $request
     * @param CategoryRepository $repository
     * @return Response
     */
    public function new(Request $request, CategoryRepository $repository): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $annonce = new Annonce();
        $form = $this->createForm(AnnonceType::class, $annonce);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid() ){

            $annonce->setUser($this->get('security.token_storage')->getToken()->getUser());
            if ($annonce->getImages() != null){
                $images = array();
                $files = $annonce->getImages();
                foreach($files as $file)
                {
                    $fileName = md5(uniqid()) . '.' . $file->guessExtension();
                    $file->move($this->getParameter('upload_directory'), $fileName);
                    array_push($images, $fileName);
                }
                $annonce->setImages($images);
            }


            $em = $this->getDoctrine()->getManager();
            $em->persist($annonce);
            $em->flush();

            return $this->redirectToRoute('annonce');
        }

        $categories = $repository->findAll();

        return $this->render('annonce/new.html.twig', [
            'form' => $form->createView(),
            "categories" => $categories,
        ]);
    }

    /**
     * @Route("/annonce/{id}/edit", name="edit_annonce")
     * @param Annonce $annonce
     * @param Request $request
     * @param CategoryRepository $repository
     * @return Response
     */
    public function edit(Annonce $annonce, Request $request, CategoryRepository $repository) : Response
    {
        $form = $this->createForm(AnnonceType::class, $annonce);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid() ){

            $annonce->setModifiedAt(new \DateTime());
            $annonce->setUser($this->get('security.token_storage')->getToken()->getUser());

            if ($annonce->getImages() != null){
                $images = array();
                $files = $annonce->getImages();
                foreach($files as $file)
                {
                    $fileName = md5(uniqid()) . '.' . $file->guessExtension();
                    $file->move($this->getParameter('upload_directory'), $fileName);
                    array_push($images, $fileName);
                }
                $annonce->setImages($images);
            }

            $em = $this->getDoctrine()->getManager();
            $em->flush();

            return $this->redirectToRoute('annonce');
        }

        $categories = $repository->findAll();

        return $this->render('annonce/edit.html.twig', [
            "form" => $form->createView(),
            "categories" => $categories,
        ]);
    }


    /**
     * @Route("/annonce/{id}/view", name="view_annonce")
     * @param Request $request
     * @param Annonce $annonce
     * @return Response
     */
    public function show(Request $request, Annonce $annonce): Response
    {
        $report = new Report();
        $form = $this->createForm(ReportType::class, $report);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $report->setReason(
                $form->get('reason')->getData()
            );
            $report->setAnnonce(
                $annonce
            );

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($report);
            $entityManager->flush();

            return $this->redirectToRoute('view_annonce', [
                'id' => $annonce->getId(),
                'message' => 'Thanks for your report'
            ]);
        }

        return $this->render('annonce/annonce.html.twig', [
            'annonce' => $annonce,
            'form' => $form->createView(),
            'message' => ''
        ]);
    }

    /**
     * @Route("/annonces/list", name="my_annonces")
     * @param AnnonceRepository $repository
     * @return Response
     */
    public function getItems(AnnonceRepository $repository): Response
    {
        $annonces = $repository->findUserAnnoncesById($this->getUser()->getId());

        return $this->render('annonce/annonce_list.html.twig', [
            'annonces' => $annonces
        ]);
    }

}

templates/annonce/annonce.html.twig
{% extends 'base.html.twig' %}

{% block title %}Annonce : {{ annonce.title }}{% endblock %}

{% block body %}

    <br><br><br>

    <!-- section -->
    <section class="section">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="details">
                        <div class="details__head">
                            <div class="details__cover">
                                <img src="{{ app.request.scheme ~'://' ~ app.request.httpHost ~ asset("./images/#{annonce.images[0]}") }}" alt="">
                            </div>

                            <div class="details__wrap">
                                <h1 class="details__title">{{ annonce.title }}</h1>

                                <ul class="details__list">
                                    <li><span>Category:</span>{{ annonce.category.name|capitalize }}</li>
                                    <li><span>Created by:</span>{{ annonce.user.username|capitalize }}</li>
                                    <li><span>Released:</span>{{ annonce.createdAt|date("m/d/Y", "Europe/Paris") }}</li>
                                    <li><span>Last update:</span>{{ annonce.modifiedAt|date("m/d/Y", "Europe/Paris") }}</li>
                                    <li>Version: </li>
                                    <li></li>
                                </ul>
                            </div>
                        </div>

                        <div class="details__text">
                            <p>{{ annonce.description }}</p>
                        </div>

                        <div class="details__gallery">
                            <div class="details__carousel owl-carousel" id="details__carousel">
                                {% for image in annonce.images %}
                                    <a href="{{ app.request.scheme ~'://' ~ app.request.httpHost ~ asset("./images/#{image}") }}" >
                                        <img src="{{ app.request.scheme ~'://' ~ app.request.httpHost ~ asset("./images/#{image}") }}" alt="">
                                    </a>
                                {% endfor %}
                            </div>

                            <button class="details__nav details__nav--prev" data-nav="#details__carousel" type="button">
                                <svg xmlns='http://www.w3.org/2000/svg' width='512' height='512' viewBox='0 0 512 512'><polyline points='328 112 184 256 328 400' style='fill:none;stroke-linecap:round;stroke-linejoin:round;stroke-width:48px'/></svg>
                            </button>
                            <button class="details__nav details__nav--next" data-nav="#details__carousel" type="button">
                                <svg xmlns='http://www.w3.org/2000/svg' width='512' height='512' viewBox='0 0 512 512'><polyline points='184 112 328 256 184 400' style='fill:none;stroke-linecap:round;stroke-linejoin:round;stroke-width:48px'/></svg>
                            </button>
                        </div>

                        <div class="details__cart">
                            <ul class="details__stat">
                                <li>
                                    <svg xmlns='http://www.w3.org/2000/svg' width='512' height='512' viewBox='0 0 512 512'>
                                        <path d='M394,480a16,16,0,0,1-9.39-3L256,383.76,127.39,477a16,16,0,0,1-24.55-18.08L153,310.35,23,221.2A16,16,0,0,1,32,192H192.38l48.4-148.95a16,16,0,0,1,30.44,0l48.4,149H480a16,16,0,0,1,9.05,29.2L359,310.35l50.13,148.53A16,16,0,0,1,394,480Z'/>
                                    </svg>
                                    <b>Note</b>
                                </li>
                            </ul>

                            <span class="details__cart-title">PRICE</span>
                            <div class="details__price">
                                <span>${{ annonce.price }}</span>
                            </div>

                            <div class="details__actions">
                                <a class="details__buy" href="{{ path('conversation_create', {'id': annonce.user.id}) }}">Contact {{ annonce.user.username|capitalize }}</a>

                                <button class="details__favorite" type="button" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                                    Report this publication
                                </button>

                                <br>

                                {% if (message == "" and app.request.get('message') == "") %}
                                {% else %}
                                    <div class="alert alert-info" role="alert"><span>{{ app.request.get('message') }}</span></div>
                                {% endif %}


                                <!-- Modal -->
                                {{ form_start(form) }}
                                <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="staticBackdropLabel">Report this publication</h5>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                            </div>
                                            <div class="modal-body">
                                                {{ form_label(form.reason) }}
                                                {{ form_widget(form.reason) }}
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                                <a href="{{ path('view_annonce', {'id': annonce.id}) }}"><button type="submit" class="btn btn-primary">Report</button></a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {{ form_end(form) }}

                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- end section -->



{% endblock %}

templates/annonce/annonce_list.html.twig
{% extends 'base.admin.html.twig' %}

{% block title %}Utilisateurs{% endblock %}

{% block body %}

    <!-- section -->
    <section class="section section--last">
        <div class="container">
            <!-- content tabs -->
            <div class="tab-content">
                <div class="tab-pane fade show active" id="tab-1" role="tabpanel">
                    <div class="row">
                        <div class="col-12">
                            <div class="table-responsive table-responsive--border">
                                <table class="profile__table">
                                    <thead>
                                    <tr>
                                        <th>Title</th>
                                        <th>Price</th>
                                        <th>Created At</th>
                                        <th>Last Modification</th>
                                        <th>Description</th>
                                        <th>Action</th>
                                    </tr>
                                    </thead>

                                    <tbody>

                                    {% for annonce in annonces %}
                                        <tr>
                                            <td>{{ annonce.title }}</td>
                                            <td>${{ annonce.price }}</td>
                                            <td>{{ annonce.createdAt|date("m/d/Y", "Europe/Paris") }}</td>
                                            <td>{{ annonce.modifiedAt|date("m/d/Y", "Europe/Paris") }}</td>
                                            <td>{{ annonce.description|slice(0, 50) }}</td>
                                            <td>
                                                <a href="{{ path('edit_annonce', {'id': annonce.id}) }}">
                                                    <button class="profile__logout" type="button">Edit</button>
                                                </a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <!-- end content tabs -->
        </div>
    </section>
    <!-- end section -->

{% endblock %}

templates/annonce/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Annonce{% endblock %}

{% block body %}

    <br><br><br>

    <!-- page title -->
    <section class="section section--last section--head" data-bg="img/bg.jpg">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="section__wrap">
                        <!-- section title -->
                        <h2 class="section__title">Edit new Annonce</h2>
                        <!-- end section title -->

                        <!-- breadcrumb -->
                        <ul class="breadcrumb">
                            <li class="breadcrumb__item"><a href="{{ path('home') }}">Home</a></li>
                            <li class="breadcrumb__item breadcrumb__item--active">Edit new Annonce</li>
                        </ul>
                        <!-- end breadcrumb -->
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- end page title -->

    <!-- section -->
    <section class="section">
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-7 col-xl-8">
                    <div class="row">
                        <!-- section title -->
                        <div class="col-12">
                            <h2 class="section__title">Edit new Annonce</h2>
                        </div>
                        <!-- end section title -->
                        {{ form_start(form) }}
                        <div class="col-12">
                            <div class="form form--contacts">
                                {{ form_widget(form.title) }}
                                {{ form_widget(form.description) }}
                                {{ form_widget(form.price) }}
                                {{ form_widget(form.images) }}
                                <br>
                                <div class="filter__select-wrap">
                                    {{ form_widget(form.category) }}
                                </div>
                                <br>
                                <button type="submit" class="form__btn">Publish</button>
                                {{ form_rest(form) }}
                            </div>
                        </div>
                        {{ form_end(form) }}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- end section -->

    <br>

{% endblock %}

templates/annonce/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Annonces{% endblock %}

{% block body %}

    <br><br><br>

    <!-- page title -->
    <section class="section section--last section--head">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="section__wrap">
                        <!-- section title -->
                        <h2 class="section__title">Annonces <span>({{ annonces|length }} offres actuellement)</span></h2>
                        <!-- end section title -->

                        <!-- breadcrumb -->
                        <ul class="breadcrumb">
                            <li class="breadcrumb__item"><a href="{{ path('home') }}">Home</a></li>
                            <li class="breadcrumb__item breadcrumb__item--active">Annonces</li>
                        </ul>
                        <!-- end breadcrumb -->
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- end page title -->

    <!-- section -->
    <section class="section section--last section--catalog">
        <div class="container">
            <!-- catalog -->
            <div class="row">


                <!-- content wrap -->
                <div class="col-12 col-lg-12">
                    <div class="row">
                        <!-- card -->
                        {% for annonce in annonces %}
                            <div class="col-12 col-sm-6 col-xl-4">
                                <div class="card">
                                    <a href="{{ path('view_annonce', {'id': annonce.id}) }}" class="card__cover">
                                        <img src="./images/{{ annonce.images[0] }}" alt="" width='512' height='300' style="object-fit: cover">
                                        <span class="card__rate">
                                        <svg xmlns='http://www.w3.org/2000/svg' width='512' height='512'
                                             viewBox='0 0 512 512'>
                                            <path d='M394,480a16,16,0,0,1-9.39-3L256,383.76,127.39,477a16,16,0,0,1-24.55-18.08L153,310.35,23,221.2A16,16,0,0,1,32,192H192.38l48.4-148.95a16,16,0,0,1,30.44,0l48.4,149H480a16,16,0,0,1,9.05,29.2L359,310.35l50.13,148.53A16,16,0,0,1,394,480Z'/>
                                        </svg>
                                        Note</span>
                                    </a>

                                    <div class="card__title">
                                        <h3>{{ annonce.title }}</h3>
                                        <p>{{ annonce.description|slice(0, 50) }}</p>
                                        <span>${{ annonce.price }}</span>
                                    </div>

                                    <div class="card__actions">
                                        <a href="{{ path('view_annonce', {'id': annonce.id}) }}">
                                            <button class="card__buy" type="button">View</button>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                        <!-- end card -->

                        <!-- paginator -->
                        <div class="col-12">
                            <div class="paginator">
                                <div class="paginator__counter">
                                    {{ annonces|length }} offres actuellement
                                </div>
                            </div>
                        </div>
                        <!-- end paginator -->


                    </div>
                </div>
                <!-- end content wrap -->
            </div>
            <!-- end catalog -->
        </div>
    </section>
    <!-- end section -->

{% endblock %}

templates/annonce/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Add Annonce{% endblock %}

{% block body %}

    <br><br><br>

    <!-- page title -->
    <section class="section section--last section--head" data-bg="img/bg.jpg">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="section__wrap">
                        <!-- section title -->
                        <h2 class="section__title">Add new Annonce</h2>
                        <!-- end section title -->

                        <!-- breadcrumb -->
                        <ul class="breadcrumb">
                            <li class="breadcrumb__item"><a href="{{ path('home') }}">Home</a></li>
                            <li class="breadcrumb__item breadcrumb__item--active">Add new Annonce</li>
                        </ul>
                        <!-- end breadcrumb -->
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- end page title -->

    <!-- section -->
    <section class="section">
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-7 col-xl-8">
                    <div class="row">
                        <!-- section title -->
                        <div class="col-12">
                            <h2 class="section__title">Add new Annonce</h2>
                        </div>
                        <!-- end section title -->
                        {{ form_start(form) }}
                        <div class="col-12">
                            <div class="form form--contacts">
                                {{ form_widget(form.title) }}
                                {{ form_widget(form.description) }}
                                {{ form_widget(form.price) }}
                                {{ form_widget(form.images) }}
                                <br>
                                <div class="filter__select-wrap">
                                    {{ form_widget(form.category) }}
                                </div>
                                <br>
                                <button type="submit" class="form__btn">Publish</button>
                                {{ form_rest(form) }}
                            </div>
                        </div>
                        {{ form_end(form) }}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- end section -->

    <br>

{% endblock %}